from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class RolloutEventType(str, Enum):
    THREAD_CREATED = "THREAD_CREATED"
    THREAD_RECOVERED = "THREAD_RECOVERED"
    RUN_STARTED = "RUN_STARTED"
    USER_MESSAGE_APPENDED = "USER_MESSAGE_APPENDED"
    CONTEXT_ASSEMBLED = "CONTEXT_ASSEMBLED"
    TOKEN_USAGE = "TOKEN_USAGE"
    MODEL_CALL_STARTED = "MODEL_CALL_STARTED"
    MODEL_CALL_COMPLETED = "MODEL_CALL_COMPLETED"
    MODEL_CALL_FAILED = "MODEL_CALL_FAILED"
    MODEL_CALL_TIMEOUT = "MODEL_CALL_TIMEOUT"
    MODEL_CALL_RETRY = "MODEL_CALL_RETRY"
    MODEL_CALL_CONTEXT_OVERFLOW = "MODEL_CALL_CONTEXT_OVERFLOW"
    AGENT_MODEL_PROTOCOL_ERROR = "AGENT_MODEL_PROTOCOL_ERROR"
    AGENT_TOOL_BUDGET_EXHAUSTED = "AGENT_TOOL_BUDGET_EXHAUSTED"
    AGENT_FINALIZATION_FALLBACK = "AGENT_FINALIZATION_FALLBACK"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    TOOL_CALL_BLOCKED = "TOOL_CALL_BLOCKED"
    TOOL_CALL_TIMEOUT = "TOOL_CALL_TIMEOUT"
    TOOL_CALL_RETRY = "TOOL_CALL_RETRY"
    TOOL_CALL_LATE_RESULT_DISCARDED = "TOOL_CALL_LATE_RESULT_DISCARDED"
    ASSISTANT_MESSAGE_APPENDED = "ASSISTANT_MESSAGE_APPENDED"
    HISTORY_TRIMMED = "HISTORY_TRIMMED"
    MEMORY_WRITTEN = "MEMORY_WRITTEN"
    MEMORY_DUPLICATE_SKIPPED = "MEMORY_DUPLICATE_SKIPPED"
    MEMORY_WRITE_FAILED = "MEMORY_WRITE_FAILED"
    MEMORY_WRITE_REJECTED = "MEMORY_WRITE_REJECTED"
    MEMORY_SEARCHED = "MEMORY_SEARCHED"
    MEMORY_INJECTED = "MEMORY_INJECTED"
    CORE_MEMORY_UPDATED = "CORE_MEMORY_UPDATED"
    CORE_MEMORY_UNCHANGED = "CORE_MEMORY_UNCHANGED"
    CORE_MEMORY_UPDATE_REJECTED = "CORE_MEMORY_UPDATE_REJECTED"
    ARCHIVAL_MEMORY_WRITTEN = "ARCHIVAL_MEMORY_WRITTEN"
    ARCHIVAL_MEMORY_DUPLICATE_SKIPPED = "ARCHIVAL_MEMORY_DUPLICATE_SKIPPED"
    ARCHIVAL_MEMORY_WRITE_FAILED = "ARCHIVAL_MEMORY_WRITE_FAILED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"


class RolloutEvent(BaseModel):
    tenant_id: Optional[str] = None
    user_id: Optional[str] = None
    agent_id: Optional[str] = None
    event_id: str
    event_type: RolloutEventType
    sequence: int
    occurred_at: str
    session_id: str
    run_id: Optional[str] = None
    message_id: Optional[str] = None
    tool_call_id: Optional[str] = None
    payload: dict = Field(default_factory=dict)


class RolloutEventStoreError(Exception):
    """Raised when rollout events cannot be persisted or loaded."""
